name: Paulo Jer么nimo's website
title: Paulo Jer么nimo - triathlon training, developing sofware, teaching ... repeat
org: Paulo Jer么nimo
author: paulojeronimo
author_url: https://github.com/paulojeronimo
base_url: ''
ctx_path: ''
haml:
  :ugly: true
asciidoctor:
  :safe: safe
  :attributes:
    sitename: Paulo Jer么nimo's website
    base_url: ''
    ctx_path: ''
    idprefix: ''
    idseparator: '-'
    sectanchors: ''
    icons: font
profiles:
  development:
    deploy: nil
  production:
    base_url: http://paulojeronimo.github.io/paulojeronimo.net
    ctx_path: /paulojeronimo.net
    asciidoctor:
      :attributes:
        base_url: http://paulojeronimo.github.io/paulojeronimo.net
        ctx_path: /paulojeronimo.net
        imagesdir: http://paulojeronimo.github.io/paulojeronimo.net/images
    deploy:
      host: github_pages
      branch: gh-pages
